const menuOptions = [
  {
    title: 'Consulta Ordens de Manutenção',
    icon: 'maintananceListIcon',
    path: '/dashboard/consulta-ordens-manutencao',
    breadCrumb: 'Consulta Ordens de Manutenção',
    id: 0,
    role: ['admin aprovador', 'admin', 'usuario', 'usuario aprovador'],
  },
  {
    title: 'Cadastro de Usuário',
    icon: 'user',
    path: '/dashboard/users',
    breadCrumb: 'Usuários',
    id: 1,
    role: ['admin aprovador', 'admin'],
  },
  {
    title: 'Cadastro de Grupo de Usuário',
    icon: 'users',
    path: '/dashboard/grupo-usuario',
    breadCrumb: 'Grupo de Usuários',
    id: 2,
    role: ['admin aprovador', 'admin'],
  },
  {
    title: 'Cadastro de Equipamentos',
    icon: 'equipmentIcon',
    path: '/dashboard/equipamentos',
    breadCrumb: 'Equipamentos',
    id: 3,
    role: ['admin aprovador', 'admin'],
  },
  {
    title: 'Cadastro de Ferramentas',
    icon: 'toolsIcon',
    path: '/dashboard/ferramentas',
    breadCrumb: 'Ferramentas',
    id: 4,
    role: ['admin aprovador', 'admin'],
  },
  {
    title: 'Cadastro de EPIs',
    icon: 'helmetIcon',
    path: '/dashboard/epis',
    breadCrumb: 'Equipamento de Proteção Individual (EPI)',
    id: 5,
    role: ['admin aprovador', 'admin'],
  },
  {
    title: 'Cadastro de Treinamentos',
    icon: 'trainingIcon',
    path: '/dashboard/treinamentos',
    breadCrumb: 'Treinamentos',
    id: 6,
    role: ['admin aprovador', 'admin'],
  },
  {
    title: 'Cadastro de Operações',
    icon: 'operationsIcon',
    path: '/dashboard/operacoes',
    breadCrumb: 'Operações',
    id: 7,
    role: ['admin aprovador', 'admin'],
  },
  {
    title: 'Ordens de Manutenção',
    icon: 'maintananceIcon',
    path: '/dashboard/ordens-manutencao',
    breadCrumb: 'Ordens de Manutenção',
    id: 8,
    role: ['admin aprovador', 'admin'],
  },
];

export default menuOptions;
